// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENTITYOBTAINED_NAN2_GAME_WORLD_H_
#define FLATBUFFERS_GENERATED_ENTITYOBTAINED_NAN2_GAME_WORLD_H_

#include "flatbuffers/flatbuffers.h"

namespace nan2 {
namespace game {
namespace world {

struct EntityObtained;

struct EntityObtained FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_TYPE = 6
  };
  uint16_t id() const {
    return GetField<uint16_t>(VT_ID, 0);
  }
  uint8_t type() const {
    return GetField<uint8_t>(VT_TYPE, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_ID) &&
           VerifyField<uint8_t>(verifier, VT_TYPE) &&
           verifier.EndTable();
  }
};

struct EntityObtainedBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint16_t id) {
    fbb_.AddElement<uint16_t>(EntityObtained::VT_ID, id, 0);
  }
  void add_type(uint8_t type) {
    fbb_.AddElement<uint8_t>(EntityObtained::VT_TYPE, type, 0);
  }
  EntityObtainedBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  EntityObtainedBuilder &operator=(const EntityObtainedBuilder &);
  flatbuffers::Offset<EntityObtained> Finish() {
    const auto end = fbb_.EndTable(start_, 2);
    auto o = flatbuffers::Offset<EntityObtained>(end);
    return o;
  }
};

inline flatbuffers::Offset<EntityObtained> CreateEntityObtained(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t id = 0,
    uint8_t type = 0) {
  EntityObtainedBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_type(type);
  return builder_.Finish();
}

}  // namespace world
}  // namespace game
}  // namespace nan2

#endif  // FLATBUFFERS_GENERATED_ENTITYOBTAINED_NAN2_GAME_WORLD_H_
