PROJ_ROOT = ../..
LIB_NAME = Math
LIB_NAMESPACE = math

include $(PROJ_ROOT)/includePre.mk

SRC_PATH = src
INC_PATH = include
TARGET_PATH = test

LIB_SRCS_NAKED = aabb.cpp vector2.cpp rect.cpp
TARGET_SRCS_NAKED = test.cpp

LIBS +=

include $(PROJ_ROOT)/includePost.mk
