// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_JOINREQ_NAN2_LOBBY_H_
#define FLATBUFFERS_GENERATED_JOINREQ_NAN2_LOBBY_H_

#include "flatbuffers/flatbuffers.h"

namespace nan2 {
namespace lobby {

struct JoinReq;

struct JoinReq FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_TOKEN = 4
  };
  const flatbuffers::String *token() const {
    return GetPointer<const flatbuffers::String *>(VT_TOKEN);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_TOKEN) &&
           verifier.Verify(token()) &&
           verifier.EndTable();
  }
};

struct JoinReqBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_token(flatbuffers::Offset<flatbuffers::String> token) {
    fbb_.AddOffset(JoinReq::VT_TOKEN, token);
  }
  JoinReqBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  JoinReqBuilder &operator=(const JoinReqBuilder &);
  flatbuffers::Offset<JoinReq> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<JoinReq>(end);
    return o;
  }
};

inline flatbuffers::Offset<JoinReq> CreateJoinReq(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> token = 0) {
  JoinReqBuilder builder_(_fbb);
  builder_.add_token(token);
  return builder_.Finish();
}

inline flatbuffers::Offset<JoinReq> CreateJoinReqDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *token = nullptr) {
  return nan2::lobby::CreateJoinReq(
      _fbb,
      token ? _fbb.CreateString(token) : 0);
}

inline const nan2::lobby::JoinReq *GetJoinReq(const void *buf) {
  return flatbuffers::GetRoot<nan2::lobby::JoinReq>(buf);
}

inline bool VerifyJoinReqBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<nan2::lobby::JoinReq>(nullptr);
}

inline void FinishJoinReqBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<nan2::lobby::JoinReq> root) {
  fbb.Finish(root);
}

}  // namespace lobby
}  // namespace nan2

#endif  // FLATBUFFERS_GENERATED_JOINREQ_NAN2_LOBBY_H_
