// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BULLET_NAN2_GAME_WORLD_H_
#define FLATBUFFERS_GENERATED_BULLET_NAN2_GAME_WORLD_H_

#include "flatbuffers/flatbuffers.h"

#include "vec2_generated.h"

namespace nan2 {
namespace game {
namespace world {

struct Bullet;

struct Bullet FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_TIME = 4,
    VT_TYPE = 6,
    VT_DIR = 8
  };
  int32_t time() const {
    return GetField<int32_t>(VT_TIME, 0);
  }
  uint8_t type() const {
    return GetField<uint8_t>(VT_TYPE, 0);
  }
  uint8_t dir() const {
    return GetField<uint8_t>(VT_DIR, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TIME) &&
           VerifyField<uint8_t>(verifier, VT_TYPE) &&
           VerifyField<uint8_t>(verifier, VT_DIR) &&
           verifier.EndTable();
  }
};

struct BulletBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_time(int32_t time) {
    fbb_.AddElement<int32_t>(Bullet::VT_TIME, time, 0);
  }
  void add_type(uint8_t type) {
    fbb_.AddElement<uint8_t>(Bullet::VT_TYPE, type, 0);
  }
  void add_dir(uint8_t dir) {
    fbb_.AddElement<uint8_t>(Bullet::VT_DIR, dir, 0);
  }
  BulletBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  BulletBuilder &operator=(const BulletBuilder &);
  flatbuffers::Offset<Bullet> Finish() {
    const auto end = fbb_.EndTable(start_, 3);
    auto o = flatbuffers::Offset<Bullet>(end);
    return o;
  }
};

inline flatbuffers::Offset<Bullet> CreateBullet(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t time = 0,
    uint8_t type = 0,
    uint8_t dir = 0) {
  BulletBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_dir(dir);
  builder_.add_type(type);
  return builder_.Finish();
}

}  // namespace world
}  // namespace game
}  // namespace nan2

#endif  // FLATBUFFERS_GENERATED_BULLET_NAN2_GAME_WORLD_H_
